<?php

namespace Biplane\YandexDirect\Api\V5\Report;

/**
 * ReportTypeEnum.
 *
 * @author Denis Vasilev
 */
final class ReportTypeEnum
{
    const ACCOUNT_PERFORMANCE_REPORT = 'ACCOUNT_PERFORMANCE_REPORT';
    const ADGROUP_PERFORMANCE_REPORT = 'ADGROUP_PERFORMANCE_REPORT';
    const AD_PERFORMANCE_REPORT = 'AD_PERFORMANCE_REPORT';
    const CAMPAIGN_PERFORMANCE_REPORT = 'CAMPAIGN_PERFORMANCE_REPORT';
    const CRITERIA_PERFORMANCE_REPORT = 'CRITERIA_PERFORMANCE_REPORT';
    const CUSTOM_REPORT = 'CUSTOM_REPORT';
    const SEARCH_QUERY_PERFORMANCE_REPORT = 'SEARCH_QUERY_PERFORMANCE_REPORT';
}
