<?php

declare(strict_types=1);

namespace Biplane\YandexDirect\Api\V5\Report;

final class ReportTypeEnum
{
    public const ACCOUNT_PERFORMANCE_REPORT = 'ACCOUNT_PERFORMANCE_REPORT';
    public const ADGROUP_PERFORMANCE_REPORT = 'ADGROUP_PERFORMANCE_REPORT';
    public const AD_PERFORMANCE_REPORT = 'AD_PERFORMANCE_REPORT';
    public const CAMPAIGN_PERFORMANCE_REPORT = 'CAMPAIGN_PERFORMANCE_REPORT';
    public const CRITERIA_PERFORMANCE_REPORT = 'CRITERIA_PERFORMANCE_REPORT';
    public const CUSTOM_REPORT = 'CUSTOM_REPORT';
    public const REACH_AND_FREQUENCY_PERFORMANCE_REPORT = 'REACH_AND_FREQUENCY_PERFORMANCE_REPORT';
    public const SEARCH_QUERY_PERFORMANCE_REPORT = 'SEARCH_QUERY_PERFORMANCE_REPORT';
}
