<?php

declare(strict_types=1);

namespace Biplane\YandexDirect\Api\V5\Contract;

use AllowDynamicProperties;

/**
 * Auto-generated code.
 */
#[AllowDynamicProperties]
class AdBuilderAdGetBase
{
//    Can be omitted.
//    protected $Creative = null;

//    Can be omitted.
//    protected $ErirAdDescription = null;

//    Can be omitted.
//    protected $AutogeneratedErirAdDescription = null;

    /**
     * @return static
     */
    public static function create()
    {
        return new static();
    }

    public function getCreative(): ?AdBuilderAdGetItem
    {
        return $this->Creative ?? null;
    }

    /**
     * @return $this
     */
    public function setCreative(?AdBuilderAdGetItem $value = null)
    {
        $this->Creative = $value;

        return $this;
    }

    public function getErirAdDescription(): ?string
    {
        return $this->ErirAdDescription ?? null;
    }

    /**
     * @return $this
     */
    public function setErirAdDescription(?string $value = null)
    {
        $this->ErirAdDescription = $value;

        return $this;
    }

    public function getAutogeneratedErirAdDescription(): ?string
    {
        return $this->AutogeneratedErirAdDescription ?? null;
    }

    /**
     * @return $this
     */
    public function setAutogeneratedErirAdDescription(?string $value = null)
    {
        $this->AutogeneratedErirAdDescription = $value;

        return $this;
    }
}
