<?php

declare(strict_types=1);

namespace Biplane\YandexDirect\Api\V5\Contract;

use AllowDynamicProperties;

/**
 * Auto-generated code.
 */
#[AllowDynamicProperties]
class AdBuilderAdGetBase
{
//    Can be omitted.
//    protected $Creative;

//    Can be omitted.
//    protected $ErirAdDescription;

//    Can be omitted.
//    protected $AutogeneratedErirAdDescription;

    /**
     * Create a new instance.
     *
     * @return static
     */
    public static function create(): static
    {
        return new static();
    }

    /**
     * Get Creative
     */
    public function getCreative(): ?AdBuilderAdGetItem
    {
        return $this->Creative ?? null;
    }

    /**
     * Set Creative
     *
     * @return $this
     */
    public function setCreative(?AdBuilderAdGetItem $value)
    {
        $this->Creative = $value;

        return $this;
    }

    /**
     * Get ErirAdDescription
     */
    public function getErirAdDescription(): ?string
    {
        return $this->ErirAdDescription ?? null;
    }

    /**
     * Set ErirAdDescription
     *
     * @return $this
     */
    public function setErirAdDescription(?string $value)
    {
        $this->ErirAdDescription = $value;

        return $this;
    }

    /**
     * Get AutogeneratedErirAdDescription
     */
    public function getAutogeneratedErirAdDescription(): ?string
    {
        return $this->AutogeneratedErirAdDescription ?? null;
    }

    /**
     * Set AutogeneratedErirAdDescription
     *
     * @return $this
     */
    public function setAutogeneratedErirAdDescription(?string $value)
    {
        $this->AutogeneratedErirAdDescription = $value;

        return $this;
    }
}
