<?php

namespace Biplane\YandexDirect\Api\V5\Contract;

/**
 * Auto-generated code.
 */
class BidModifierTypeEnum
{

    const MOBILE_ADJUSTMENT = 'MOBILE_ADJUSTMENT';

    const DESKTOP_ADJUSTMENT = 'DESKTOP_ADJUSTMENT';

    const DEMOGRAPHICS_ADJUSTMENT = 'DEMOGRAPHICS_ADJUSTMENT';

    const RETARGETING_ADJUSTMENT = 'RETARGETING_ADJUSTMENT';

    const REGIONAL_ADJUSTMENT = 'REGIONAL_ADJUSTMENT';

    const VIDEO_ADJUSTMENT = 'VIDEO_ADJUSTMENT';

    const SMART_AD_ADJUSTMENT = 'SMART_AD_ADJUSTMENT';


}

