<?php

namespace Biplane\YandexDirect\Api\V5\Contract;

/**
 * Auto-generated code.
 */
class CpmBannerCampaignSettingsGetEnum
{

    const ADD_OPENSTAT_TAG = 'ADD_OPENSTAT_TAG';

    const ADD_METRICA_TAG = 'ADD_METRICA_TAG';

    const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';

    const ENABLE_AREA_OF_INTEREST_TARGETING = 'ENABLE_AREA_OF_INTEREST_TARGETING';

    const ENABLE_SITE_MONITORING = 'ENABLE_SITE_MONITORING';

    const REQUIRE_SERVICING = 'REQUIRE_SERVICING';

    const SHARED_ACCOUNT_ENABLED = 'SHARED_ACCOUNT_ENABLED';

    const DAILY_BUDGET_ALLOWED = 'DAILY_BUDGET_ALLOWED';


}

