<?php

namespace Biplane\YandexDirect\Api\V5\Contract;

/**
 * Auto-generated code.
 */
class CpmBannerCampaignNetworkStrategyTypeEnum
{

    const MANUAL_CPM = 'MANUAL_CPM';

    const WB_DECREASED_PRICE_FOR_REPEATED_IMPRESSIONS = 'WB_DECREASED_PRICE_FOR_REPEATED_IMPRESSIONS';

    const CP_DECREASED_PRICE_FOR_REPEATED_IMPRESSIONS = 'CP_DECREASED_PRICE_FOR_REPEATED_IMPRESSIONS';

    const WB_MAXIMUM_IMPRESSIONS = 'WB_MAXIMUM_IMPRESSIONS';

    const CP_MAXIMUM_IMPRESSIONS = 'CP_MAXIMUM_IMPRESSIONS';

    const WB_AVERAGE_CPV = 'WB_AVERAGE_CPV';

    const CP_AVERAGE_CPV = 'CP_AVERAGE_CPV';

    const UNKNOWN = 'UNKNOWN';


}

