<?php

namespace Biplane\YandexDirect\Api\V5\Contract;

/**
 * Auto-generated code.
 */
class DynamicTextCampaignSettingsGetEnum
{

    const ADD_OPENSTAT_TAG = 'ADD_OPENSTAT_TAG';

    const ADD_METRICA_TAG = 'ADD_METRICA_TAG';

    const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';

    const ENABLE_AREA_OF_INTEREST_TARGETING = 'ENABLE_AREA_OF_INTEREST_TARGETING';

    const ENABLE_SITE_MONITORING = 'ENABLE_SITE_MONITORING';

    const ENABLE_BEHAVIORAL_TARGETING = 'ENABLE_BEHAVIORAL_TARGETING';

    const REQUIRE_SERVICING = 'REQUIRE_SERVICING';

    const ENABLE_EXTENDED_AD_TITLE = 'ENABLE_EXTENDED_AD_TITLE';

    const ENABLE_COMPANY_INFO = 'ENABLE_COMPANY_INFO';

    const SHARED_ACCOUNT_ENABLED = 'SHARED_ACCOUNT_ENABLED';

    const DAILY_BUDGET_ALLOWED = 'DAILY_BUDGET_ALLOWED';

    const CAMPAIGN_EXACT_PHRASE_MATCHING_ENABLED = 'CAMPAIGN_EXACT_PHRASE_MATCHING_ENABLED';


}

