<?php

declare(strict_types=1);

namespace Biplane\YandexDirect\Api\V5\Contract;

/**
 * Auto-generated code.
 */
class DynamicTextCampaignSettingsGetEnum
{
    public const ADD_OPENSTAT_TAG = 'ADD_OPENSTAT_TAG';

    public const ADD_METRICA_TAG = 'ADD_METRICA_TAG';

    public const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';

    public const ENABLE_AREA_OF_INTEREST_TARGETING = 'ENABLE_AREA_OF_INTEREST_TARGETING';

    public const ENABLE_CURRENT_AREA_TARGETING = 'ENABLE_CURRENT_AREA_TARGETING';

    public const ENABLE_REGULAR_AREA_TARGETING = 'ENABLE_REGULAR_AREA_TARGETING';

    public const ENABLE_SITE_MONITORING = 'ENABLE_SITE_MONITORING';

    public const ENABLE_BEHAVIORAL_TARGETING = 'ENABLE_BEHAVIORAL_TARGETING';

    public const REQUIRE_SERVICING = 'REQUIRE_SERVICING';

    public const ENABLE_EXTENDED_AD_TITLE = 'ENABLE_EXTENDED_AD_TITLE';

    public const ENABLE_COMPANY_INFO = 'ENABLE_COMPANY_INFO';

    public const SHARED_ACCOUNT_ENABLED = 'SHARED_ACCOUNT_ENABLED';

    public const DAILY_BUDGET_ALLOWED = 'DAILY_BUDGET_ALLOWED';

    public const CAMPAIGN_EXACT_PHRASE_MATCHING_ENABLED = 'CAMPAIGN_EXACT_PHRASE_MATCHING_ENABLED';
}
