<?php

declare(strict_types=1);

namespace Biplane\YandexDirect\Api\V5\Contract;

use AllowDynamicProperties;

/**
 * Auto-generated code.
 */
#[AllowDynamicProperties]
class GetAdsRequest extends GetRequestGeneral
{
    /** @var AdsSelectionCriteria */
    protected $SelectionCriteria;

    /** @var non-empty-list<'AdCategories'|'AgeLabel'|'AdGroupId'|'CampaignId'|'Id'|'State'|'Status'|'StatusClarification'|'Type'|'Subtype'> */
    protected $FieldNames;

//    Can be omitted.
//    protected $TextAdFieldNames;

//    Can be omitted.
//    protected $TextAdPriceExtensionFieldNames;

//    Can be omitted.
//    protected $MobileAppAdFieldNames;

//    Can be omitted.
//    protected $DynamicTextAdFieldNames;

//    Can be omitted.
//    protected $TextImageAdFieldNames;

//    Can be omitted.
//    protected $MobileAppImageAdFieldNames;

//    Can be omitted.
//    protected $TextAdBuilderAdFieldNames;

//    Can be omitted.
//    protected $MobileAppAdBuilderAdFieldNames;

//    Can be omitted.
//    protected $MobileAppCpcVideoAdBuilderAdFieldNames;

//    Can be omitted.
//    protected $CpmBannerAdBuilderAdFieldNames;

//    Can be omitted.
//    protected $CpcVideoAdBuilderAdFieldNames;

//    Can be omitted.
//    protected $CpmVideoAdBuilderAdFieldNames;

//    Can be omitted.
//    protected $SmartAdBuilderAdFieldNames;

//    Can be omitted.
//    protected $ShoppingAdFieldNames;

//    Can be omitted.
//    protected $ListingAdFieldNames;

//    Can be omitted.
//    protected $ResponsiveAdFieldNames;

    /**
     * Create a new instance.
     *
     * @return static
     */
    public static function create()
    {
        return new static();
    }

    /**
     * Get SelectionCriteria
     */
    public function getSelectionCriteria(): AdsSelectionCriteria
    {
        return $this->SelectionCriteria;
    }

    /**
     * Set SelectionCriteria
     *
     * @return $this
     */
    public function setSelectionCriteria(AdsSelectionCriteria $value)
    {
        $this->SelectionCriteria = $value;

        return $this;
    }

    /**
     * Get FieldNames
     *
     * @see \Biplane\YandexDirect\Api\V5\Contract\AdFieldEnum
     *
     * @return non-empty-list<'AdCategories'|'AgeLabel'|'AdGroupId'|'CampaignId'|'Id'|'State'|'Status'|'StatusClarification'|'Type'|'Subtype'>
     */
    public function getFieldNames(): array
    {
        return $this->FieldNames;
    }

    /**
     * Set FieldNames
     *
     * @see \Biplane\YandexDirect\Api\V5\Contract\AdFieldEnum
     *
     * @param non-empty-list<'AdCategories'|'AgeLabel'|'AdGroupId'|'CampaignId'|'Id'|'State'|'Status'|'StatusClarification'|'Type'|'Subtype'> $value
     *
     * @return $this
     */
    public function setFieldNames(array $value)
    {
        $this->FieldNames = $value;

        return $this;
    }

    /**
     * Get TextAdFieldNames
     *
     * @see \Biplane\YandexDirect\Api\V5\Contract\TextAdFieldEnum
     *
     * @return list<'AdImageHash'|'DisplayDomain'|'FinalUrl'|'Href'|'SitelinkSetId'|'Text'|'Title'|'Title2'|'Mobile'|'VCardId'|'DisplayUrlPath'|'AdImageModeration'|'SitelinksModeration'|'VCardModeration'|'AdExtensions'|'DisplayUrlPathModeration'|'VideoExtension'|'TurboPageId'|'TurboPageModeration'|'BusinessId'|'PreferVCardOverBusiness'|'ErirAdDescription'|'AutogeneratedErirAdDescription'>
     */
    public function getTextAdFieldNames(): array
    {
        return $this->TextAdFieldNames ?? [];
    }

    /**
     * Set TextAdFieldNames
     *
     * @see \Biplane\YandexDirect\Api\V5\Contract\TextAdFieldEnum
     *
     * @param list<'AdImageHash'|'DisplayDomain'|'FinalUrl'|'Href'|'SitelinkSetId'|'Text'|'Title'|'Title2'|'Mobile'|'VCardId'|'DisplayUrlPath'|'AdImageModeration'|'SitelinksModeration'|'VCardModeration'|'AdExtensions'|'DisplayUrlPathModeration'|'VideoExtension'|'TurboPageId'|'TurboPageModeration'|'BusinessId'|'PreferVCardOverBusiness'|'ErirAdDescription'|'AutogeneratedErirAdDescription'> $value
     *
     * @return $this
     */
    public function setTextAdFieldNames(array $value)
    {
        $this->TextAdFieldNames = $value;

        return $this;
    }

    /**
     * Get TextAdPriceExtensionFieldNames
     *
     * @see \Biplane\YandexDirect\Api\V5\Contract\TextAdPriceExtensionFieldEnum
     *
     * @return list<'Price'|'OldPrice'|'PriceCurrency'|'PriceQualifier'>
     */
    public function getTextAdPriceExtensionFieldNames(): array
    {
        return $this->TextAdPriceExtensionFieldNames ?? [];
    }

    /**
     * Set TextAdPriceExtensionFieldNames
     *
     * @see \Biplane\YandexDirect\Api\V5\Contract\TextAdPriceExtensionFieldEnum
     *
     * @param list<'Price'|'OldPrice'|'PriceCurrency'|'PriceQualifier'> $value
     *
     * @return $this
     */
    public function setTextAdPriceExtensionFieldNames(array $value)
    {
        $this->TextAdPriceExtensionFieldNames = $value;

        return $this;
    }

    /**
     * Get MobileAppAdFieldNames
     *
     * @see \Biplane\YandexDirect\Api\V5\Contract\MobileAppAdFieldEnum
     *
     * @return list<'AdImageHash'|'Title'|'Text'|'Features'|'Action'|'TrackingUrl'|'AdImageModeration'|'VideoExtension'|'ErirAdDescription'|'AutogeneratedErirAdDescription'>
     */
    public function getMobileAppAdFieldNames(): array
    {
        return $this->MobileAppAdFieldNames ?? [];
    }

    /**
     * Set MobileAppAdFieldNames
     *
     * @see \Biplane\YandexDirect\Api\V5\Contract\MobileAppAdFieldEnum
     *
     * @param list<'AdImageHash'|'Title'|'Text'|'Features'|'Action'|'TrackingUrl'|'AdImageModeration'|'VideoExtension'|'ErirAdDescription'|'AutogeneratedErirAdDescription'> $value
     *
     * @return $this
     */
    public function setMobileAppAdFieldNames(array $value)
    {
        $this->MobileAppAdFieldNames = $value;

        return $this;
    }

    /**
     * Get DynamicTextAdFieldNames
     *
     * @see \Biplane\YandexDirect\Api\V5\Contract\DynamicTextAdFieldEnum
     *
     * @return list<'AdImageHash'|'SitelinkSetId'|'Text'|'VCardId'|'AdImageModeration'|'SitelinksModeration'|'VCardModeration'|'AdExtensions'>
     */
    public function getDynamicTextAdFieldNames(): array
    {
        return $this->DynamicTextAdFieldNames ?? [];
    }

    /**
     * Set DynamicTextAdFieldNames
     *
     * @see \Biplane\YandexDirect\Api\V5\Contract\DynamicTextAdFieldEnum
     *
     * @param list<'AdImageHash'|'SitelinkSetId'|'Text'|'VCardId'|'AdImageModeration'|'SitelinksModeration'|'VCardModeration'|'AdExtensions'> $value
     *
     * @return $this
     */
    public function setDynamicTextAdFieldNames(array $value)
    {
        $this->DynamicTextAdFieldNames = $value;

        return $this;
    }

    /**
     * Get TextImageAdFieldNames
     *
     * @see \Biplane\YandexDirect\Api\V5\Contract\TextImageAdFieldEnum
     *
     * @return list<'AdImageHash'|'FinalUrl'|'Href'|'TurboPageId'|'TurboPageModeration'|'ErirAdDescription'|'AutogeneratedErirAdDescription'>
     */
    public function getTextImageAdFieldNames(): array
    {
        return $this->TextImageAdFieldNames ?? [];
    }

    /**
     * Set TextImageAdFieldNames
     *
     * @see \Biplane\YandexDirect\Api\V5\Contract\TextImageAdFieldEnum
     *
     * @param list<'AdImageHash'|'FinalUrl'|'Href'|'TurboPageId'|'TurboPageModeration'|'ErirAdDescription'|'AutogeneratedErirAdDescription'> $value
     *
     * @return $this
     */
    public function setTextImageAdFieldNames(array $value)
    {
        $this->TextImageAdFieldNames = $value;

        return $this;
    }

    /**
     * Get MobileAppImageAdFieldNames
     *
     * @see \Biplane\YandexDirect\Api\V5\Contract\MobileAppImageAdFieldEnum
     *
     * @return list<'AdImageHash'|'TrackingUrl'|'ErirAdDescription'|'AutogeneratedErirAdDescription'>
     */
    public function getMobileAppImageAdFieldNames(): array
    {
        return $this->MobileAppImageAdFieldNames ?? [];
    }

    /**
     * Set MobileAppImageAdFieldNames
     *
     * @see \Biplane\YandexDirect\Api\V5\Contract\MobileAppImageAdFieldEnum
     *
     * @param list<'AdImageHash'|'TrackingUrl'|'ErirAdDescription'|'AutogeneratedErirAdDescription'> $value
     *
     * @return $this
     */
    public function setMobileAppImageAdFieldNames(array $value)
    {
        $this->MobileAppImageAdFieldNames = $value;

        return $this;
    }

    /**
     * Get TextAdBuilderAdFieldNames
     *
     * @see \Biplane\YandexDirect\Api\V5\Contract\TextAdBuilderAdFieldEnum
     *
     * @return list<'Creative'|'FinalUrl'|'Href'|'TurboPageId'|'TurboPageModeration'|'ErirAdDescription'|'AutogeneratedErirAdDescription'>
     */
    public function getTextAdBuilderAdFieldNames(): array
    {
        return $this->TextAdBuilderAdFieldNames ?? [];
    }

    /**
     * Set TextAdBuilderAdFieldNames
     *
     * @see \Biplane\YandexDirect\Api\V5\Contract\TextAdBuilderAdFieldEnum
     *
     * @param list<'Creative'|'FinalUrl'|'Href'|'TurboPageId'|'TurboPageModeration'|'ErirAdDescription'|'AutogeneratedErirAdDescription'> $value
     *
     * @return $this
     */
    public function setTextAdBuilderAdFieldNames(array $value)
    {
        $this->TextAdBuilderAdFieldNames = $value;

        return $this;
    }

    /**
     * Get MobileAppAdBuilderAdFieldNames
     *
     * @see \Biplane\YandexDirect\Api\V5\Contract\MobileAppAdBuilderAdFieldEnum
     *
     * @return list<'Creative'|'TrackingUrl'|'ErirAdDescription'|'AutogeneratedErirAdDescription'>
     */
    public function getMobileAppAdBuilderAdFieldNames(): array
    {
        return $this->MobileAppAdBuilderAdFieldNames ?? [];
    }

    /**
     * Set MobileAppAdBuilderAdFieldNames
     *
     * @see \Biplane\YandexDirect\Api\V5\Contract\MobileAppAdBuilderAdFieldEnum
     *
     * @param list<'Creative'|'TrackingUrl'|'ErirAdDescription'|'AutogeneratedErirAdDescription'> $value
     *
     * @return $this
     */
    public function setMobileAppAdBuilderAdFieldNames(array $value)
    {
        $this->MobileAppAdBuilderAdFieldNames = $value;

        return $this;
    }

    /**
     * Get MobileAppCpcVideoAdBuilderAdFieldNames
     *
     * @see \Biplane\YandexDirect\Api\V5\Contract\MobileAppCpcVideoAdBuilderAdFieldEnum
     *
     * @return list<'Creative'|'TrackingUrl'|'ErirAdDescription'|'AutogeneratedErirAdDescription'>
     */
    public function getMobileAppCpcVideoAdBuilderAdFieldNames(): array
    {
        return $this->MobileAppCpcVideoAdBuilderAdFieldNames ?? [];
    }

    /**
     * Set MobileAppCpcVideoAdBuilderAdFieldNames
     *
     * @see \Biplane\YandexDirect\Api\V5\Contract\MobileAppCpcVideoAdBuilderAdFieldEnum
     *
     * @param list<'Creative'|'TrackingUrl'|'ErirAdDescription'|'AutogeneratedErirAdDescription'> $value
     *
     * @return $this
     */
    public function setMobileAppCpcVideoAdBuilderAdFieldNames(array $value)
    {
        $this->MobileAppCpcVideoAdBuilderAdFieldNames = $value;

        return $this;
    }

    /**
     * Get CpmBannerAdBuilderAdFieldNames
     *
     * @see \Biplane\YandexDirect\Api\V5\Contract\CpmBannerAdBuilderAdFieldEnum
     *
     * @return list<'Creative'|'Href'|'TrackingPixels'|'TurboPageId'|'TurboPageModeration'|'ErirAdDescription'|'AutogeneratedErirAdDescription'>
     */
    public function getCpmBannerAdBuilderAdFieldNames(): array
    {
        return $this->CpmBannerAdBuilderAdFieldNames ?? [];
    }

    /**
     * Set CpmBannerAdBuilderAdFieldNames
     *
     * @see \Biplane\YandexDirect\Api\V5\Contract\CpmBannerAdBuilderAdFieldEnum
     *
     * @param list<'Creative'|'Href'|'TrackingPixels'|'TurboPageId'|'TurboPageModeration'|'ErirAdDescription'|'AutogeneratedErirAdDescription'> $value
     *
     * @return $this
     */
    public function setCpmBannerAdBuilderAdFieldNames(array $value)
    {
        $this->CpmBannerAdBuilderAdFieldNames = $value;

        return $this;
    }

    /**
     * Get CpcVideoAdBuilderAdFieldNames
     *
     * @see \Biplane\YandexDirect\Api\V5\Contract\CpcVideoAdBuilderAdFieldEnum
     *
     * @return list<'Creative'|'Href'|'TurboPageId'|'TurboPageModeration'|'ErirAdDescription'|'AutogeneratedErirAdDescription'>
     */
    public function getCpcVideoAdBuilderAdFieldNames(): array
    {
        return $this->CpcVideoAdBuilderAdFieldNames ?? [];
    }

    /**
     * Set CpcVideoAdBuilderAdFieldNames
     *
     * @see \Biplane\YandexDirect\Api\V5\Contract\CpcVideoAdBuilderAdFieldEnum
     *
     * @param list<'Creative'|'Href'|'TurboPageId'|'TurboPageModeration'|'ErirAdDescription'|'AutogeneratedErirAdDescription'> $value
     *
     * @return $this
     */
    public function setCpcVideoAdBuilderAdFieldNames(array $value)
    {
        $this->CpcVideoAdBuilderAdFieldNames = $value;

        return $this;
    }

    /**
     * Get CpmVideoAdBuilderAdFieldNames
     *
     * @see \Biplane\YandexDirect\Api\V5\Contract\CpmVideoAdBuilderAdFieldEnum
     *
     * @return list<'Creative'|'Href'|'TrackingPixels'|'TurboPageId'|'TurboPageModeration'|'ErirAdDescription'|'AutogeneratedErirAdDescription'>
     */
    public function getCpmVideoAdBuilderAdFieldNames(): array
    {
        return $this->CpmVideoAdBuilderAdFieldNames ?? [];
    }

    /**
     * Set CpmVideoAdBuilderAdFieldNames
     *
     * @see \Biplane\YandexDirect\Api\V5\Contract\CpmVideoAdBuilderAdFieldEnum
     *
     * @param list<'Creative'|'Href'|'TrackingPixels'|'TurboPageId'|'TurboPageModeration'|'ErirAdDescription'|'AutogeneratedErirAdDescription'> $value
     *
     * @return $this
     */
    public function setCpmVideoAdBuilderAdFieldNames(array $value)
    {
        $this->CpmVideoAdBuilderAdFieldNames = $value;

        return $this;
    }

    /**
     * Get SmartAdBuilderAdFieldNames
     *
     * @see \Biplane\YandexDirect\Api\V5\Contract\SmartAdBuilderAdFieldEnum
     *
     * @return list<'Creative'>
     */
    public function getSmartAdBuilderAdFieldNames(): array
    {
        return $this->SmartAdBuilderAdFieldNames ?? [];
    }

    /**
     * Set SmartAdBuilderAdFieldNames
     *
     * @see \Biplane\YandexDirect\Api\V5\Contract\SmartAdBuilderAdFieldEnum
     *
     * @param list<'Creative'> $value
     *
     * @return $this
     */
    public function setSmartAdBuilderAdFieldNames(array $value)
    {
        $this->SmartAdBuilderAdFieldNames = $value;

        return $this;
    }

    /**
     * Get ShoppingAdFieldNames
     *
     * @see \Biplane\YandexDirect\Api\V5\Contract\ShoppingAdFieldEnum
     *
     * @return list<'SitelinkSetId'|'SitelinksModeration'|'AdExtensions'|'BusinessId'|'FeedId'|'FeedFilterConditions'|'FeedProcessingStatus'|'TitleSources'|'TextSources'|'DefaultTexts'>
     */
    public function getShoppingAdFieldNames(): array
    {
        return $this->ShoppingAdFieldNames ?? [];
    }

    /**
     * Set ShoppingAdFieldNames
     *
     * @see \Biplane\YandexDirect\Api\V5\Contract\ShoppingAdFieldEnum
     *
     * @param list<'SitelinkSetId'|'SitelinksModeration'|'AdExtensions'|'BusinessId'|'FeedId'|'FeedFilterConditions'|'FeedProcessingStatus'|'TitleSources'|'TextSources'|'DefaultTexts'> $value
     *
     * @return $this
     */
    public function setShoppingAdFieldNames(array $value)
    {
        $this->ShoppingAdFieldNames = $value;

        return $this;
    }

    /**
     * Get ListingAdFieldNames
     *
     * @see \Biplane\YandexDirect\Api\V5\Contract\ListingAdFieldEnum
     *
     * @return list<'SitelinkSetId'|'SitelinksModeration'|'AdExtensions'|'BusinessId'|'FeedId'|'FeedFilterConditions'|'FeedProcessingStatus'|'TitleSources'|'TextSources'|'DefaultTexts'>
     */
    public function getListingAdFieldNames(): array
    {
        return $this->ListingAdFieldNames ?? [];
    }

    /**
     * Set ListingAdFieldNames
     *
     * @see \Biplane\YandexDirect\Api\V5\Contract\ListingAdFieldEnum
     *
     * @param list<'SitelinkSetId'|'SitelinksModeration'|'AdExtensions'|'BusinessId'|'FeedId'|'FeedFilterConditions'|'FeedProcessingStatus'|'TitleSources'|'TextSources'|'DefaultTexts'> $value
     *
     * @return $this
     */
    public function setListingAdFieldNames(array $value)
    {
        $this->ListingAdFieldNames = $value;

        return $this;
    }

    /**
     * Get ResponsiveAdFieldNames
     *
     * @see \Biplane\YandexDirect\Api\V5\Contract\ResponsiveAdFieldEnum
     *
     * @return list<'AdImages'|'DisplayDomain'|'Href'|'SitelinkSetId'|'Texts'|'Titles'|'DisplayUrlPath'|'SitelinksModeration'|'AdExtensions'|'DisplayUrlPathModeration'|'PriceExtension'|'VideoExtensions'|'BusinessId'|'ErirAdDescription'>
     */
    public function getResponsiveAdFieldNames(): array
    {
        return $this->ResponsiveAdFieldNames ?? [];
    }

    /**
     * Set ResponsiveAdFieldNames
     *
     * @see \Biplane\YandexDirect\Api\V5\Contract\ResponsiveAdFieldEnum
     *
     * @param list<'AdImages'|'DisplayDomain'|'Href'|'SitelinkSetId'|'Texts'|'Titles'|'DisplayUrlPath'|'SitelinksModeration'|'AdExtensions'|'DisplayUrlPathModeration'|'PriceExtension'|'VideoExtensions'|'BusinessId'|'ErirAdDescription'> $value
     *
     * @return $this
     */
    public function setResponsiveAdFieldNames(array $value)
    {
        $this->ResponsiveAdFieldNames = $value;

        return $this;
    }
}
