<?php

declare(strict_types=1);

namespace Biplane\YandexDirect\Api\V5\Contract;

use AllowDynamicProperties;

/**
 * Auto-generated code.
 */
#[AllowDynamicProperties]
class MobileAppAdBuilderAdFieldEnum
{
    public const string CREATIVE = 'Creative';

    public const string TRACKING_URL = 'TrackingUrl';

    public const string ERIR_AD_DESCRIPTION = 'ErirAdDescription';

    public const string AUTOGENERATED_ERIR_AD_DESCRIPTION = 'AutogeneratedErirAdDescription';
}
