<?php

declare(strict_types=1);

namespace Biplane\YandexDirect\Api\V5\Contract;

/**
 * Auto-generated code.
 */
class MobileAppAdFieldEnum
{
    public const AD_IMAGE_HASH = 'AdImageHash';

    public const TITLE = 'Title';

    public const TEXT = 'Text';

    public const FEATURES = 'Features';

    public const ACTION = 'Action';

    public const TRACKING_URL = 'TrackingUrl';

    public const AD_IMAGE_MODERATION = 'AdImageModeration';

    public const VIDEO_EXTENSION = 'VideoExtension';

    public const ERIR_AD_DESCRIPTION = 'ErirAdDescription';

    public const AUTOGENERATED_ERIR_AD_DESCRIPTION = 'AutogeneratedErirAdDescription';
}
