<?php

namespace Biplane\YandexDirect\Api\V5\Contract;

/**
 * Auto-generated code.
 */
class MobileAppCampaignSettingsEnum
{

    const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';

    const ENABLE_AREA_OF_INTEREST_TARGETING = 'ENABLE_AREA_OF_INTEREST_TARGETING';

    const ENABLE_BEHAVIORAL_TARGETING = 'ENABLE_BEHAVIORAL_TARGETING';

    const ENABLE_AUTOFOCUS = 'ENABLE_AUTOFOCUS';

    const REQUIRE_SERVICING = 'REQUIRE_SERVICING';

    const MAINTAIN_NETWORK_CPC = 'MAINTAIN_NETWORK_CPC';

    const CAMPAIGN_EXACT_PHRASE_MATCHING_ENABLED = 'CAMPAIGN_EXACT_PHRASE_MATCHING_ENABLED';


}

