<?php

declare(strict_types=1);

namespace Biplane\YandexDirect\Api\V5\Contract;

/**
 * Auto-generated code.
 */
class MobileAppAdBuilderAdFieldEnum
{
    public const CREATIVE = 'Creative';

    public const TRACKING_URL = 'TrackingUrl';

    public const ERIR_AD_DESCRIPTION = 'ErirAdDescription';

    public const AUTOGENERATED_ERIR_AD_DESCRIPTION = 'AutogeneratedErirAdDescription';
}
