<?php

declare(strict_types=1);

namespace Biplane\YandexDirect\Api\V5\Contract;

use AllowDynamicProperties;
use Override;

/**
 * Auto-generated code.
 */
#[AllowDynamicProperties]
class MobileAppAdGet extends MobileAppAdBase
{
//    Can be omitted.
//    protected $Features;

//    Can be omitted.
//    protected $AdImageModeration;

//    Can be omitted.
//    protected $VideoExtension;

//    Can be omitted.
//    protected $AutogeneratedErirAdDescription;

    /**
     * Create a new instance.
     *
     * @return static
     */
    #[Override]
    public static function create(): static
    {
        return new static();
    }

    /**
     * Get Features
     *
     * @return list<MobileAppAdFeatureGetItem>
     */
    public function getFeatures(): array
    {
        return $this->Features ?? [];
    }

    /**
     * Set Features
     *
     * @param list<MobileAppAdFeatureGetItem> $value
     *
     * @return $this
     */
    public function setFeatures(array $value)
    {
        $this->Features = $value;

        return $this;
    }

    /**
     * Get AdImageModeration
     */
    public function getAdImageModeration(): ?ExtensionModeration
    {
        return $this->AdImageModeration ?? null;
    }

    /**
     * Set AdImageModeration
     *
     * @return $this
     */
    public function setAdImageModeration(?ExtensionModeration $value)
    {
        $this->AdImageModeration = $value;

        return $this;
    }

    /**
     * Get VideoExtension
     */
    public function getVideoExtension(): ?VideoExtensionGetItem
    {
        return $this->VideoExtension ?? null;
    }

    /**
     * Set VideoExtension
     *
     * @return $this
     */
    public function setVideoExtension(?VideoExtensionGetItem $value)
    {
        $this->VideoExtension = $value;

        return $this;
    }

    /**
     * Get AutogeneratedErirAdDescription
     */
    public function getAutogeneratedErirAdDescription(): ?string
    {
        return $this->AutogeneratedErirAdDescription ?? null;
    }

    /**
     * Set AutogeneratedErirAdDescription
     *
     * @return $this
     */
    public function setAutogeneratedErirAdDescription(?string $value)
    {
        $this->AutogeneratedErirAdDescription = $value;

        return $this;
    }
}
