<?php

namespace Biplane\YandexDirect\Api\V5\Contract;

/**
 * Auto-generated code.
 */
class SmartCampaignSearchStrategyTypeEnum
{

    const AVERAGE_CPC_PER_CAMPAIGN = 'AVERAGE_CPC_PER_CAMPAIGN';

    const AVERAGE_CPC_PER_FILTER = 'AVERAGE_CPC_PER_FILTER';

    const AVERAGE_CPA_PER_CAMPAIGN = 'AVERAGE_CPA_PER_CAMPAIGN';

    const AVERAGE_CPA_PER_FILTER = 'AVERAGE_CPA_PER_FILTER';

    const PAY_FOR_CONVERSION_PER_CAMPAIGN = 'PAY_FOR_CONVERSION_PER_CAMPAIGN';

    const PAY_FOR_CONVERSION_PER_FILTER = 'PAY_FOR_CONVERSION_PER_FILTER';

    const AVERAGE_ROI = 'AVERAGE_ROI';

    const AVERAGE_CRR = 'AVERAGE_CRR';

    const SERVING_OFF = 'SERVING_OFF';

    const UNKNOWN = 'UNKNOWN';


}

