<?php

declare(strict_types=1);

namespace Biplane\YandexDirect\Api\V5\Contract;

use AllowDynamicProperties;

/**
 * Auto-generated code.
 */
#[AllowDynamicProperties]
class TextAdFieldEnum
{
    public const string AD_IMAGE_HASH = 'AdImageHash';

    public const string DISPLAY_DOMAIN = 'DisplayDomain';

    public const string FINAL_URL = 'FinalUrl';

    public const string HREF = 'Href';

    public const string SITELINK_SET_ID = 'SitelinkSetId';

    public const string TEXT = 'Text';

    public const string TITLE = 'Title';

    public const string TITLE2 = 'Title2';

    public const string MOBILE = 'Mobile';

    public const string V_CARD_ID = 'VCardId';

    public const string DISPLAY_URL_PATH = 'DisplayUrlPath';

    public const string AD_IMAGE_MODERATION = 'AdImageModeration';

    public const string SITELINKS_MODERATION = 'SitelinksModeration';

    public const string V_CARD_MODERATION = 'VCardModeration';

    public const string AD_EXTENSIONS = 'AdExtensions';

    public const string DISPLAY_URL_PATH_MODERATION = 'DisplayUrlPathModeration';

    public const string VIDEO_EXTENSION = 'VideoExtension';

    public const string TURBO_PAGE_ID = 'TurboPageId';

    public const string TURBO_PAGE_MODERATION = 'TurboPageModeration';

    public const string BUSINESS_ID = 'BusinessId';

    public const string PREFER_V_CARD_OVER_BUSINESS = 'PreferVCardOverBusiness';

    public const string ERIR_AD_DESCRIPTION = 'ErirAdDescription';

    public const string AUTOGENERATED_ERIR_AD_DESCRIPTION = 'AutogeneratedErirAdDescription';
}
