<?php

declare(strict_types=1);

namespace Biplane\YandexDirect\Api\V5\Contract;

/**
 * Auto-generated code.
 */
class TextAdBuilderAdFieldEnum
{
    public const CREATIVE = 'Creative';

    public const FINAL_URL = 'FinalUrl';

    public const HREF = 'Href';

    public const TURBO_PAGE_ID = 'TurboPageId';

    public const TURBO_PAGE_MODERATION = 'TurboPageModeration';

    public const ERIR_AD_DESCRIPTION = 'ErirAdDescription';

    public const AUTOGENERATED_ERIR_AD_DESCRIPTION = 'AutogeneratedErirAdDescription';
}
