<?php

declare(strict_types=1);

namespace Biplane\YandexDirect\Api\V5\Contract;

use AllowDynamicProperties;

/**
 * Auto-generated code.
 */
#[AllowDynamicProperties]
class TextImageAdFieldEnum
{
    public const string AD_IMAGE_HASH = 'AdImageHash';

    public const string FINAL_URL = 'FinalUrl';

    public const string HREF = 'Href';

    public const string TURBO_PAGE_ID = 'TurboPageId';

    public const string TURBO_PAGE_MODERATION = 'TurboPageModeration';

    public const string ERIR_AD_DESCRIPTION = 'ErirAdDescription';

    public const string AUTOGENERATED_ERIR_AD_DESCRIPTION = 'AutogeneratedErirAdDescription';
}
