<?php

declare(strict_types=1);

namespace Biplane\YandexDirect\Api\V5\Contract;

/**
 * Auto-generated code.
 */
class TextCampaignSettingsEnum
{
    public const EXCLUDE_PAUSED_COMPETING_ADS = 'EXCLUDE_PAUSED_COMPETING_ADS';

    public const ADD_OPENSTAT_TAG = 'ADD_OPENSTAT_TAG';

    public const ADD_METRICA_TAG = 'ADD_METRICA_TAG';

    public const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';

    public const ENABLE_AREA_OF_INTEREST_TARGETING = 'ENABLE_AREA_OF_INTEREST_TARGETING';

    public const ENABLE_CURRENT_AREA_TARGETING = 'ENABLE_CURRENT_AREA_TARGETING';

    public const ENABLE_REGULAR_AREA_TARGETING = 'ENABLE_REGULAR_AREA_TARGETING';

    public const ENABLE_SITE_MONITORING = 'ENABLE_SITE_MONITORING';

    public const ENABLE_BEHAVIORAL_TARGETING = 'ENABLE_BEHAVIORAL_TARGETING';

    public const ENABLE_AUTOFOCUS = 'ENABLE_AUTOFOCUS';

    public const REQUIRE_SERVICING = 'REQUIRE_SERVICING';

    public const ENABLE_RELATED_KEYWORDS = 'ENABLE_RELATED_KEYWORDS';

    public const ENABLE_EXTENDED_AD_TITLE = 'ENABLE_EXTENDED_AD_TITLE';

    public const MAINTAIN_NETWORK_CPC = 'MAINTAIN_NETWORK_CPC';

    public const ENABLE_COMPANY_INFO = 'ENABLE_COMPANY_INFO';

    public const CAMPAIGN_EXACT_PHRASE_MATCHING_ENABLED = 'CAMPAIGN_EXACT_PHRASE_MATCHING_ENABLED';
}
