<?php

declare(strict_types=1);

namespace Biplane\YandexDirect\Api\V5\Reports;

final class ReportTypeEnum
{
    public const string ACCOUNT_PERFORMANCE_REPORT = 'ACCOUNT_PERFORMANCE_REPORT';
    public const string ADGROUP_PERFORMANCE_REPORT = 'ADGROUP_PERFORMANCE_REPORT';
    public const string AD_PERFORMANCE_REPORT = 'AD_PERFORMANCE_REPORT';
    public const string CAMPAIGN_PERFORMANCE_REPORT = 'CAMPAIGN_PERFORMANCE_REPORT';
    public const string CRITERIA_PERFORMANCE_REPORT = 'CRITERIA_PERFORMANCE_REPORT';
    public const string CUSTOM_REPORT = 'CUSTOM_REPORT';
    public const string REACH_AND_FREQUENCY_PERFORMANCE_REPORT = 'REACH_AND_FREQUENCY_PERFORMANCE_REPORT';
    public const string SEARCH_QUERY_PERFORMANCE_REPORT = 'SEARCH_QUERY_PERFORMANCE_REPORT';
}
